apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: default
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.4.0"
    helm:
      releaseName: ingress-nginx
      passCredentials: false
      parameters:
        - name: installCRDs
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
