

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: default
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rancher
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "2.8.2"
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
